# Generated by Django 5.0.3 on 2024-11-05 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_account_account_number_account_bank_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(default=1, max_length=20, unique=True),
        ),
    ]
